version: '2'
services:
  microserviceconsumerfeignhystrix1:
    image: wucy.docker/microservice-consumer-feign-hystrix:latest
    hostname: microserviceconsumerfeignhystrix1
    ports:
      - "7001:7001"

networks:
  default:
    external:
      name: springcloud-demo
