info:
  app:
  name: wucy-microservice-provider
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@
  spring:
    source: @spring.version@
    target: @spring.version@