server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-consumer-feign-hystrix


logging:
  level: debug
info:
  app:
  name: wucy
  encoding: @project.build.sourceEncoding@
  java:
    source: @java.version@
    target: @java.version@
  spring:
    source: @spring.version@
    target: @spring.version@


